#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 18 06:00:46 2020

@author: som
"""

# Imports
import numpy as np
np.random.seed(100)
from tensorflow import random
random.set_seed(100)

import os
import pathlib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
os.chdir('/Users/som/Dropbox/Complex_systems_RNN/DL_tutorial')
from Kij import Kij
from scipy.stats import beta
from scipy.interpolate import interp1d
from scipy.stats import uniform
from statsmodels.distributions.empirical_distribution import ECDF

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import regularizers
print(tf.__version__)
import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling

# Import Rec dataset EQ and HURR

dataset_path = '/Users/som/Dropbox/Complex_systems_RNN/Data/Multihazards/MH_10IM.csv'
dataset = pd.read_csv(dataset_path)
dataset.pop("IM")
dataset.pop("Time")
a1 = 1.0
b1 = 1.0
loc1 = 0
sca1 = 1

def transform(Rec):
    return np.power((1-Rec),1/1)
    
def invtransform(x):
    return (1-np.power(x,1))
    
dataset['Rec'] = transform(dataset['Rec'])
dataset['P1'] = transform(dataset['P1'])
dataset['P2'] = transform(dataset['P2'])
dataset.tail()

train_dataset = dataset.sample(frac=1.0,random_state=100)
test_dataset = dataset.drop(train_dataset.index)
train_stats = train_dataset.describe()
train_stats.pop("Rec")
train_stats = train_stats.transpose()
train_stats

train_labels = train_dataset.pop('Rec')
test_labels = test_dataset.pop('Rec')

def norm(x):
  return (x - train_stats['mean']) / train_stats['std']
normed_train_data = norm(train_dataset)
normed_test_data = norm(test_dataset)

def build_model():
          model = keras.Sequential([
            layers.Dense(4, activation='softmax', input_shape=[len(train_dataset.keys())],bias_initializer='zeros'),
            layers.Dense(4, activation='softmax',bias_initializer='zeros'),
            layers.Dense(1,bias_initializer='zeros')
          ])
        
          # optimizer = tf.keras.optimizers.RMSprop(0.001)
          optimizer = tf.keras.optimizers.RMSprop(0.001)
        
          model.compile(loss='mse',
                        optimizer=optimizer,
                        metrics=['mae', 'mse'])
          return model

model_MH = build_model()

EPOCHS = 3000

history = model_MH.fit(
  normed_train_data, train_labels,
  epochs=EPOCHS, validation_split = 0.0, verbose=0,
  callbacks=[tfdocs.modeling.EpochDots()],shuffle = False)

hist = pd.DataFrame(history.history)
hist['epoch'] = history.epoch
hist.tail()

## Predict one MH recovery curve

Tim2 = np.arange(1,1001,1)

file1 = '/Users/som/Dropbox/Complex_systems_RNN/Data/Multihazards/MH_Comp.csv'
TPM1 = pd.read_csv(file1)
K12_ex = ECDF(TPM1['T1'])
K23_ex = ECDF(TPM1['T2'])

Dis_tim3 = Kij(IM=105,Haz='Hurr',time=Tim2)
A1,A2 = Dis_tim3.Time()
# A1 = A1[0:850]
# A2 = A2[0:850]
A1[0] = 0
A2[0] = 0
# A1[len(A1)-1] = 1
# A2[len(A2)-1] = 1

dat_MH = pd.DataFrame(Tim2,columns=['Time'])
K = K12_ex(Tim2)
dat_MH['P1'] = A1.reshape(len(dat_MH['Time']),1) # K.reshape(len(Tim2),1)
K = K23_ex(Tim2)
dat_MH['P2'] = A2.reshape(len(dat_MH['Time']),1) # K.reshape(len(Tim2),1)
dat_MH['P1'] = transform(dat_MH['P1'])
dat_MH['P2'] = transform(dat_MH['P2'])
dat_MH.pop("Time")
normed_dat_MH = norm(dat_MH)
dat_pred_MH = invtransform(model_MH.predict(normed_dat_MH).flatten())

file_MH = '/Users/som/Dropbox/Complex_systems_RNN/Data/Multihazards/MH_exact_EH_125_70_150.csv' # '/Users/som/Dropbox/Complex_systems_RNN/Data/Multihazards/MH_test.csv'
MH_exact = pd.read_csv(file_MH)
plt.plot(MH_exact['Time'],MH_exact['Rec'])
plt.plot(Tim2,dat_pred_MH)
plt.ylim([0,1.0])